### ISSUE TITLE
Routes translation

### ISSUE THREAD

**Issue by MrUpsidown** [dobromir-hristov/vue-i18n-starter#2]
Great starter kit! Any suggestion on how I could also translate the routes paths using your project as a base? ie. if I want to have /en/contact and /de/kontakt etc.

**Comment by dobromir-hristov** [comment]
You would need to have dynamic route definitions, or match using regex. This however would make route definitions much harder to write out.

**Comment by MrUpsidown** [comment]
What about having the routes defined in each language?

**Comment by dobromir-hristov** [comment]
Too manual, but it will work.
