### ISSUE TITLE
Q: update data on locale change

### ISSUE THREAD

**Issue by 0dp** [dobromir-hristov/vue-i18n-starter#3]
If i wanted to save the current locale on form submit from Home.vue

I have tried something like this:
```
  data () {
    return {
      form: {
        locale: this.$i18n.locale
      },
      submitted: false
    }
  },
```
While I can see the value of `this.$i18n.locale` change when using the language switcher. The value of `form.locale` does not change with it.

Since you cant use `:value` and `:model` on the same input element. I am kind of lost.

I know this is by design, but I don't really understand how I can accomplish this

**Comment by dobromir-hristov** [comment]
@0dp sorry for the late reply.
If you save it like this, you do not actually change the language, you just save the currently chosen language.

You would need a watcher to watch for changes on that property and update your form.

**Comment by antfu** [comment]
@0dp maybe this would work
```js
computed: {
  locale() {
    return this.$i18n.locale
  }
}
```

**Comment by 0dp** [comment]
Thanks, I will give it a shot
